[project]
name = ""
version = ""
description = ""
authors = [
    {name = "pythonplayer123", email = "admin@pythonplayer123.xyz"},
]
dependencies = [
    "discord>=2.3.2",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "BSD-3-Clause"}

